version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    volumes:
      - /root/v2ray/config.json:/etc/v2ray/config.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /root/v2ray/sock:/sock
  tls-shunt-proxy:
    image: hqhyco/tls-shunt-proxy:latest
    container_name: tls-shunt-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - /root/tls-shunt-proxy/config.yaml:/etc/tls-shunt-proxy/config.yaml
      - /root/tls-shunt-proxy/certificates:/etc/ssl/tls-shunt-proxy/certificates
      - /root/tls-shunt-proxy/www:/var/www/html
      - /root/v2ray/sock:/sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - v2ray
  trojan:
    image: p4gefau1t/trojan-go:latest
    container_name: trojan
    restart: always
#    ports:
#      - 3567:3567
    volumes:
      - /root/trojan/config.json:/etc/trojan-go/config.json